server:
  port: 8082
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manufacture_technology_model?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: MQa12345
  devtools:
    restart:
      enabled: true
# feign configuration
feign:
  httpclient:
    enabled: true
    hc5:
      enabled: false
    disable-ssl-validation: false # 禁用 SSL 验证
    max-connections: 200 # 最大连接
    max-connections-per-route: 50 # 路由最大连接数
    time-to-live: 900 # 连接存活时间
    time-to-live-unit: seconds # 连接存活时间单位
    follow-redirects: true # 重定向
    connection-timeout: 2000 # 连接超时
    connection-timer-repeat: 3000 # 连接重复间隔
  okhttp:
    enabled: false


springdoc:
  swagger-ui:
    path: /


mybatis-plus:
  mapper-locations: classpath*:resources/mapper/*.xml
  type-aliases-package: top.atluofu.**.dao
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  file:
    path: /log/${spring.application.name}
  config: classpath:log/logback-spring.xml
  level:
    root: info

minio:
  endpoint: http://127.0.0.1:9000 #Minio服务所在地址
  bucketName: technologyModel #存储桶名称
  accessKey: technologyModel #访问的key
  secretKey: technologyModel #访问的秘钥