# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-14 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsrecord',
            name='datatime',
            field=models.DateTimeField(default=b'2018-11-14', verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
