spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: masterData
          uri: lb://masterData
#          uri: http://localhost:8081
          predicates:
            - Path=/masterData/**
          filters:
            - StripPrefix=1
        - id: manufactureMachineModel
          uri: lb://manufactureMachineModel
          predicates:
            - Path=/manufactureMachineModel/**
          filters:
            - StripPrefix=1
        - id: manufactureModel
          uri: lb://manufactureModel
          predicates:
            - Path= /manufactureModel/**
          filters:
            - StripPrefix=1
        - id: manufactureTechnologyModel
          uri: lb://manufactureTechnologyModel
          predicates:
            - Path=/technology/**
          filters:
            - StripPrefix=1

#yml配置
logging:
  file:
    path: /log/${spring.application.name}
  config: classpath:log/logback-spring.xml
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: info

