spring:
  application:
    name: wsmModel
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        namespace: fa745b2a-47f5-4418-8635-b7baacc638a1
        group: DEFAULT_GROUP
        file-extension: yaml
  datasource:
    url: jdbc:mysql://localhost:3306/mom_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: MQa12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:resources/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0


feign:
  httpclient:
    enabled: true
    hc5:
      enabled: false
    disable-ssl-validation: false # 禁用 SSL 验证
    max-connections: 200 # 最大连接
    max-connections-per-route: 50 # 路由最大连接数
    time-to-live: 900 # 连接存活时间
    time-to-live-unit: seconds # 连接存活时间单位
    follow-redirects: true # 重定向
    connection-timeout: 2000 # 连接超时
    connection-timer-repeat: 3000 # 连接重复间隔
  okhttp:
    enabled: false

server:
  port: 8888

minio:
  endpoint: http://127.0.0.1:9000 #Minio服务所在地址
  bucketName: wmsModel #存储桶名称
  accessKey: wmsModel #访问的key
  secretKey: wmsModel #访问的秘钥